services:
  llm-tests:
    image: llm-service
    container_name: llm-tests
    volumes:
      - ./tests:/app/tests
    environment:
      - BASE_URL=http://llm-service:8000
    command: >
      python tests/eval_models.py
      --base-url http://llm-service:8000
    networks:
      - default
    profiles:
      - test

  llm-quality-tests:
    image: llm-service
    container_name: llm-quality-tests
    volumes:
      - ./tests:/app/tests
    environment:
      - BASE_URL=http://llm-service:8000
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
    command: >
      python tests/test_llm_quality.py
      --base-url http://llm-service:8000
    networks:
      - default
    profiles:
      - test-quality

networks:
  default:
    name: personal-finance-llm-service_default
    external: true
